### ISSUE TITLE
Guard Duty Miner not working with recent Minemeld Docker Version 0.9.68

### ISSUE THREAD

**Issue by m5systems** [mrichardson03/aws-guardduty-miner#7]
Hi,

   I installed the 0.v2 extension update that you did for me a year ago. When I clone the node and reboot the engine keeps restarting before I can even configure in a inbound feed with credentials.  I have tried to commit and restart after each step and it still hangs up the system.  Any thoughts.

**Comment by m5systems** [comment]
Hi,  Not sure if anyone else has seen this.  I did fresh install and still have the same issue

**Comment by mrichardson03** [comment]
The engine startup issue should be fixed in v0.2.1.

I don't use this extension any more, and if you use it you should fork and take over maintaining it.

**Comment by m5systems** [comment]
Michael,

  Thanks for the update.  Its working great again.
Much appreciated.



Art
________________________________
